version: "3.9"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=temsaude
      - DB_NAME=temsaude_desafio
      - DB_DIALECT=postgres
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=temsaude
      - POSTGRES_DB=temsaude_desafio
volumes:
  logvolume01: {}
